CREATE TABLE LAROATLB_REGION_CLIENTE (
  ID_REGION NUMBER,
  NOMBRE_REGION VARCHAR2(50),
  CONSTRAINT PK_LAROATLB_REGION_CLIENTE PRIMARY KEY(ID_REGION)
);

CREATE TABLE LAROATLB_CLIENTE (
  ID_CLIENTE NUMBER,
  NOMBRE VARCHAR2(80),
  APELLIDO1 VARCHAR2(30),
  APELLIDO2 VARCHAR2(30),
  TELEFONO NUMBER,
  EMAIL VARCHAR2(80),
  ID_REGION NUMBER,
  CONSTRAINT PK_LAROATLB_CLIENTE PRIMARY KEY(ID_CLIENTE),
  CONSTRAINT FK_LAROATLB_CLIENTE_REGION FOREIGN KEY(ID_REGION) REFERENCES LAROATLB_REGION_CLIENTE(ID_REGION)
);

CREATE TABLE LAROATLB_COMUNA_CLIENTE (
  ID_COMUNA NUMBER,
  NOMBRE_COMUNA VARCHAR2(50),
  ID_REGION NUMBER,
  ID_CALLE NUMBER,
  CONSTRAINT PK_LAROATLB_COMUNA_CLIENTE PRIMARY KEY(ID_COMUNA),
  CONSTRAINT FK_LAROATLB_COMUNA_REGION FOREIGN KEY(ID_REGION) REFERENCES LAROATLB_REGION_CLIENTE(ID_REGION)
);

CREATE TABLE LAROATLB_CALLE_CLIENTE (
  ID_CALLE NUMBER,
  NOMBRE_CALLE VARCHAR2(50),
  NUMERO_CALLE NUMBER,
  CONSTRAINT PK_LAROATLB_CALLE_CLIENTE PRIMARY KEY(ID_CALLE)
);

CREATE TABLE LAROATLB_MASCOTA (
  ID_MASCOTA NUMBER,
  NOMBRE VARCHAR2(80),
  EDAD NUMBER,
  ID_CLIENTE NUMBER,
  ID_ESPECIE NUMBER,
  CONSTRAINT PK_LAROATLB_MASCOTA PRIMARY KEY(ID_MASCOTA),
  CONSTRAINT FK_LAROATLB_MASCOTA_CLIENTE FOREIGN KEY(ID_CLIENTE) REFERENCES LAROATLB_CLIENTE(ID_CLIENTE),
  CONSTRAINT FK_LAROATLB_MASCOTA_ESPECIE FOREIGN KEY(ID_ESPECIE) REFERENCES LAROATLB_ESPECIE(ID_ESPECIE)
);

CREATE TABLE LAROATLB_ESPECIE (
  ID_ESPECIE NUMBER,
  NOMBRE_ESPECIE VARCHAR2(50),
  CONSTRAINT PK_LAROATLB_ESPECIE PRIMARY KEY(ID_ESPECIE)
);

CREATE TABLE LAROATLB_RAZA (
  ID_RAZA NUMBER,
  NOMBRE_RAZA VARCHAR2(50),
  ID_ESPECIE NUMBER,
  CONSTRAINT PK_LAROATLB_RAZA PRIMARY KEY(ID_RAZA),
  CONSTRAINT FK_LAROATLB_RAZA_ESPECIE FOREIGN KEY(ID_ESPECIE) REFERENCES LAROATLB_ESPECIE(ID_ESPECIE)
);

CREATE TABLE LAROATLB_CITA (
  ID_CITA NUMBER,
  FECHA DATE,
  ID_MASCOTA NUMBER,
  ID_VETERINARIO NUMBER,
  CONSTRAINT PK_LAROATLB_CITA PRIMARY KEY(ID_CITA),
  CONSTRAINT FK_LAROATLB_CITA_MASCOTA FOREIGN KEY(ID_MASCOTA) REFERENCES LAROATLB_MASCOTA(ID_MASCOTA),
  CONSTRAINT FK_LAROATLB_CITA_VETERINARIO FOREIGN KEY(ID_VETERINARIO) REFERENCES LAROATLB_VETERINARIO(ID_VETERINARIO)
);

CREATE TABLE LAROATLB_VETERINARIO (
  ID_VETERINARIO NUMBER,
  NOMBRE VARCHAR2(80),
  APELLIDO1 VARCHAR2(30),
  APELLIDO2 VARCHAR2(30),
  ESPECIALIDAD VARCHAR2(50),
  TELEFONO NUMBER,
  EMAIL VARCHAR2(80),
  CONSTRAINT PK_LAROATLB_VETERINARIO PRIMARY KEY(ID_VETERINARIO)
);

CREATE TABLE LAROATLB_TRATAMIENTO (
  ID_TRATAMIENTO NUMBER,
  DESCRIPCION VARCHAR2(300),
  FECHA DATE,
  ID_MASCOTA NUMBER,
  ID_VETERINARIO NUMBER,
  CONSTRAINT PK_LAROATLB_TRATAMIENTO PRIMARY KEY(ID_TRATAMIENTO),
  CONSTRAINT FK_LAROATLB_TRATAMIENTO_MASCOTA FOREIGN KEY(ID_MASCOTA) REFERENCES LAROATLB_MASCOTA(ID_MASCOTA),
  CONSTRAINT FK_LAROATLB_TRATAMIENTO_VETERINARIO FOREIGN KEY(ID_VETERINARIO) REFERENCES LAROATLB_VETERINARIO(ID_VETERINARIO)
);

CREATE TABLE LAROATLB_HISTORIAL_MEDICO (
  ID_HISTORIAL NUMBER,
  FECHA DATE,
  DESCRIPCION VARCHAR2(300),
  ID_MASCOTA NUMBER,
  ID_VETERINARIO NUMBER,
  CONSTRAINT PK_LAROATLB_HISTORIAL_MEDICO PRIMARY KEY(ID_HISTORIAL),
  CONSTRAINT FK_LAROATLB_HISTORIAL_MASCOTA FOREIGN KEY(ID_MASCOTA) REFERENCES LAROATLB_MASCOTA(ID_MASCOTA),
  CONSTRAINT FK_LAROATLB_HISTORIAL_VETERINARIO FOREIGN KEY(ID_VETERINARIO) REFERENCES LAROATLB_VETERINARIO(ID_VETERINARIO)
);

CREATE TABLE LAROATLB_VENTA (
  ID_VENTA NUMBER,
  FECHA DATE,
  ID_CLIENTE NUMBER,
  CONSTRAINT PK_LAROATLB_VENTA PRIMARY KEY(ID_VENTA),
  CONSTRAINT FK_LAROATLB_VENTA_CLIENTE FOREIGN KEY(ID_CLIENTE) REFERENCES LAROATLB_CLIENTE(ID_CLIENTE)
);

CREATE TABLE LAROATLB_PRODUCTO (
  ID_PRODUCTO NUMBER,
  NOMBRE VARCHAR2(80),
  PRECIO NUMBER,
  STOCK NUMBER,
  ID_CATEGORIA NUMBER,
  CONSTRAINT PK_LAROATLB_PRODUCTO PRIMARY KEY(ID_PRODUCTO),
  CONSTRAINT FK_LAROATLB_PRODUCTO_CATEGORIA FOREIGN KEY(ID_CATEGORIA) REFERENCES LAROATLB_CATEGORIA(ID_CATEGORIA)
);

CREATE TABLE LAROATLB_CATEGORIA (
  ID_CATEGORIA NUMBER,
  NOMBRE VARCHAR2(80),
  CONSTRAINT PK_LAROATLB_CATEGORIA PRIMARY KEY(ID_CATEGORIA)
);

CREATE TABLE LAROATLB_DETALLE_VENTA (
  ID_DETALLE NUMBER,
  ID_VENTA NUMBER,
  ID_PRODUCTO NUMBER,
  CANTIDAD NUMBER,
  PRECIO NUMBER,
  CONSTRAINT PK_LAROATLB_DETALLE_VENTA PRIMARY KEY(ID_DETALLE),
  CONSTRAINT FK_LAROATLB_DETALLE_VENTA FOREIGN KEY(ID_VENTA) REFERENCES LAROATLB_VENTA(ID_VENTA),
  CONSTRAINT FK_LAROATLB_DETALLE_PRODUCTO FOREIGN KEY(ID_PRODUCTO) REFERENCES LAROATLB_PRODUCTO(ID_PRODUCTO)
);

CREATE TABLE LAROATLB_FACTURA (
  ID_FACTURA NUMBER,
  FECHA DATE,
  NOMBRE_PRODUCTO VARCHAR2(100),
  PRECIO NUMBER,
  CANTIDAD NUMBER,
  CONSTRAINT PK_LAROATLB_FACTURA PRIMARY KEY(ID_FACTURA)
);

CREATE TABLE LAROATLB_DETALLE_PRODUCTO_PROVEEDOR_FACTURA (
  ID_PRODUCTO NUMBER,
  ID_PROVEEDOR NUMBER,
  ID_FACTURA NUMBER,
  PRECIO NUMBER,
  CANTIDAD NUMBER,
  CONSTRAINT PK_LAROATLB_DETALLE_PRODUCTO_PROVEEDOR_FACTURA PRIMARY KEY(ID_PRODUCTO, ID_PROVEEDOR, ID_FACTURA),
  CONSTRAINT FK_LAROATLB_DETALLE_PROD_PROV FOREIGN KEY(ID_PRODUCTO) REFERENCES LAROATLB_PRODUCTO(ID_PRODUCTO),
  CONSTRAINT FK_LAROATLB_DETALLE_PROV FACTURA FOREIGN KEY(ID_FACTURA) REFERENCES LAROATLB_FACTURA(ID_FACTURA)
);

CREATE TABLE LAROATLB_PROVEEDOR (
  ID_PROVEEDOR NUMBER,
  NOMBRE VARCHAR2(80),
  TELEFONO NUMBER,
  EMAIL VARCHAR2(80),
  ID_REGION NUMBER,
  CONSTRAINT PK_LAROATLB_PROVEEDOR PRIMARY KEY(ID_PROVEEDOR),
  CONSTRAINT FK_LAROATLB_PROVEEDOR_REGION FOREIGN KEY(ID_REGION) REFERENCES LAROATLB_REGION_CLIENTE(ID_REGION)
);

CREATE TABLE LAROATLB_REGION_PROVEEDOR (
  ID_REGION NUMBER,
  NOMBRE_REGION VARCHAR2(50),
  CONSTRAINT PK_LAROATLB_REGION_PROVEEDOR PRIMARY KEY(ID_REGION)
);

CREATE TABLE LAROATLB_COMUNA_PROVEEDOR (
  ID_COMUNA NUMBER,
  NOMBRE_COMUNA VARCHAR2(50),
  ID_REGION NUMBER,
  ID_CALLE NUMBER,
  CONSTRAINT PK_LAROATLB_COMUNA_PROVEEDOR PRIMARY KEY(ID_COMUNA),
  CONSTRAINT FK_LAROATLB_COMUNA_PROVEEDOR_REGION FOREIGN KEY(ID_REGION) REFERENCES LAROATLB_REGION_PROVEEDOR(ID_REGION)
);

CREATE TABLE LAROATLB_CALLE_PROVEEDOR (
  ID_CALLE NUMBER,
  NOMBRE_CALLE VARCHAR2(50),
  NUMERO_CALLE NUMBER,
  CONSTRAINT PK_LAROATLB_CALLE_PROVEEDOR PRIMARY KEY(ID_CALLE)
);

CREATE TABLE LAROATLB_DETALLE_VETERINARIO_TRATAMIENTO (
  ID_VETERINARIO NUMBER,
  ID_TRATAMIENTO NUMBER,
  CONSTRAINT PK_LAROATLB_DETALLE_VET_TRATAMIENTO PRIMARY KEY(ID_VETERINARIO, ID_TRATAMIENTO),
  CONSTRAINT FK_LAROATLB_DETALLE_VET FOREIGN KEY(ID_VETERINARIO) REFERENCES LAROATLB_VETERINARIO(ID_VETERINARIO),
  CONSTRAINT FK_LAROATLB_DETALLE_TRATAMIENTO FOREIGN KEY(ID_TRATAMIENTO) REFERENCES LAROATLB_TRATAMIENTO(ID_TRATAMIENTO)
);
