-- GENERA CORREO VETENIRARIO
CREATE OR REPLACE FUNCTION LAROATLB_GENERA_CORREO_VETE(
    NOMBRE_F VARCHAR2,
    APELLIDO1_F VARCHAR2,
    APELLIDO2_F VARCHAR2)
RETURN VARCHAR2
IS  
    EMAIL VARCHAR2(100) := '';
    CANTIDAD NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO CANTIDAD
    FROM LAROATLB_VETERINARIO
    WHERE (UPPER(SUBSTR(NOMBRE,1,2)) = UPPER(SUBSTR(NOMBRE_F,1,2))) AND ( UPPER(SUBSTR(APELLIDO1,3,2)) = UPPER(SUBSTR(APELLIDO1_F,3,2))) AND ( UPPER(APELLIDO2) = UPPER(APELLIDO2_F));
    IF (CANTIDAD = 0) THEN
        EMAIL:= CONCAT(SUBSTR(NOMBRE_F,1,2),CONCAT(SUBSTR(APELLIDO1_F,3,2),CONCAT('.',CONCAT(APELLIDO2_F,'@VETSOL.CL'))));
    ELSE 
        EMAIL:= CONCAT(SUBSTR(NOMBRE_F,1,2),CONCAT(SUBSTR(APELLIDO1_F,3,2),CONCAT('.',CONCAT(CONCAT(APELLIDO2_F,TO_CHAR(CANTIDAD)),'@VETSOL.CL'))));
    END IF;
    RETURN (EMAIL);
END;    

-- GENERA CORREO SECRETARIA
CREATE OR REPLACE FUNCTION LAROATLB_GENERA_CORREO_SECRE(
    NOMBRE_F VARCHAR2,
    APELLIDO1_F VARCHAR2,
    APELLIDO2_F VARCHAR2)
RETURN VARCHAR2
IS  
    EMAIL VARCHAR2(100) := '';
    CANTIDAD NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO CANTIDAD
    FROM LAROATLB_SECRETARIA
    WHERE (UPPER(SUBSTR(NOMBRE,1,2)) = UPPER(SUBSTR(NOMBRE_F,1,2))) AND ( UPPER(SUBSTR(APELLIDO1,3,2)) = UPPER(SUBSTR(APELLIDO1_F,3,2))) AND ( UPPER(APELLIDO2) = UPPER(APELLIDO2_F));
    IF (CANTIDAD = 0) THEN
        EMAIL:= CONCAT(SUBSTR(NOMBRE_F,1,2),CONCAT(SUBSTR(APELLIDO1_F,3,2),CONCAT('.',CONCAT(APELLIDO2_F,'@VETSOL.CL'))));
    ELSE 
        EMAIL:= CONCAT(SUBSTR(NOMBRE_F,1,2),CONCAT(SUBSTR(APELLIDO1_F,3,2),CONCAT('.',CONCAT(CONCAT(APELLIDO2_F,TO_CHAR(CANTIDAD)),'@VETSOL.CL'))));
    END IF;
    RETURN (EMAIL);
END;    

