BEGIN
LAROATLB(1,'ARICA Y PARINACOTA');
LAROATLB(2,'TAPARACA');
LAROATLB(3,'ANTOFAGASTA');
LAROATLB(4,'ATACAMA');
LAROATLB(5,'COQUIMBO');
LAROATLB(6,'VALPARAISO');
LAROATLB(7,'METROPOLITANA DE SANTIAGO');
LAROATLB(8,'LIBERTADOR GENERAL BERNARDO O´HIGGINS');
LAROATLB(9,'MAULE');
LAROATLB(10,'ÑUBLE');
LAROATLB(11,'BIOBIO');
LAROATLB(12,'LA ARAUCANIA');
LAROATLB(13,'LOS RIOS');
LAROATLB(14,'LOS LAGOS');
LAROATLB(15,'AYSEN DEL GENERAL CARLOS IBAÑEZ DEL CAMPO');
LAROATLB(16,'MAGALLANES');
END;

Arica y Parinacota
Tarapacá
Antofagasta
Atacama
Coquimbo
Valparaíso
Metropolitana de Santiago
Libertador General Bernardo O'Higgins
Maule
Ñuble
Biobío
La Araucanía
Los Ríos
Los Lagos
Aysén del General Carlos Ibáñez del Campo
Magallanes y de la Antártica Chilena
