BEGIN
  LAROATLB_GESTIONAR_REGIONES('C','MAULE');
END;

BEGIN
LAROATLB_GESTIONA_COMUNA('C','TALCA',1);
LAROATLB_GESTIONA_COMUNA('C','COLBUN',1);
LAROATLB_GESTIONA_COMUNA('C','CAUQUENES',1);
LAROATLB_GESTIONA_COMUNA('C','CURICO',1);
LAROATLB_GESTIONA_COMUNA('C','CONSTITUCION',1);
LAROATLB_GESTIONA_COMUNA('C','EMPEDRADO',1);
LAROATLB_GESTIONA_COMUNA('C','HUALAÑE',1);
LAROATLB_GESTIONA_COMUNA('C','CUREPTO',1);
LAROATLB_GESTIONA_COMUNA('C','PELARCO',1);
LAROATLB_GESTIONA_COMUNA('C','PENCAHUE',1);
LAROATLB_GESTIONA_COMUNA('C','RIO CLARO',1);
LAROATLB_GESTIONA_COMUNA('C','SAN CLEMENTE',1);
LAROATLB_GESTIONA_COMUNA('C','SAGRADA FAMILIA',1);
LAROATLB_GESTIONA_COMUNA('C','MAULE',1);
LAROATLB_GESTIONA_COMUNA('C','SAN RAFAEL',1);
LAROATLB_GESTIONA_COMUNA('C','CHANCO',1);
LAROATLB_GESTIONA_COMUNA('C','PELLUHUE',1);
LAROATLB_GESTIONA_COMUNA('C','LICANTEN',1);
LAROATLB_GESTIONA_COMUNA('C','MOLINA',1);
LAROATLB_GESTIONA_COMUNA('C','RAUCO',1);
LAROATLB_GESTIONA_COMUNA('C','ROMERAL',1);
LAROATLB_GESTIONA_COMUNA('C','TENO',1);
LAROATLB_GESTIONA_COMUNA('C','VICHUQUEN',1);
LAROATLB_GESTIONA_COMUNA('C','LINARES',1);
LAROATLB_GESTIONA_COMUNA('C','COLBUN',1);
LAROATLB_GESTIONA_COMUNA('C','LONGAVI',1);
LAROATLB_GESTIONA_COMUNA('C','PARRAL',1);
LAROATLB_GESTIONA_COMUNA('C','RETIRO',1);
LAROATLB_GESTIONA_COMUNA('C','SAN JAVIER',1);
LAROATLB_GESTIONA_COMUNA('C','VILLA ALEGRE',1);
LAROATLB_GESTIONA_COMUNA('C','YERBAS BUENAS',1);
END;
