-- Triggers para PK
CREATE OR REPLACE TRIGGER LAROATLB_ID_CLIENTE
  BEFORE INSERT 
  ON LAROATLB_CLIENTE
  FOR EACH ROW
DECLARE
BEGIN
  SELECT NVL(MAX(ID_CLIENTE),0)+1 INTO :NEW.ID_CLIENTE
  FROM LAROATLB_CLIENTE;
END;


CREATE OR REPLACE TRIGGER LAROATLB_ID_SECRETARIA
  BEFORE INSERT
  ON LAROATLB_SECRETARIA
  FOR EACH ROW
DECLARE
BEGIN
  SELECT NVL(MAX(ID_SECRE),0)+1 INTO :NEW.ID_SECRE
  FROM LAROATLB_SECRETARIA;
END;


CREATE OR REPLACE TRIGGER LAROATLB_ID_MASCOTA
  BEFORE INSERT 
  ON LAROATLB_MASCOTA
  FOR EACH ROW
DECLARE
BEGIN
  SELECT NVL(MAX(ID_MASCOTA),0)+1 INTO :NEW.ID_MASCOTA
  FROM LAROATLB_MASCOTA;
END;

CREATE OR REPLACE TRIGGER LAROATLB_ID_REGION
  BEFORE INSERT 
  ON LAROATLB_REGION_CLIENTE
  FOR EACH ROW
DECLARE
BEGIN
  -- Obtener el valor máximo de ID_REGION y sumarle 1 para el nuevo registro
  SELECT NVL(MAX(ID_REGION), 0) + 1 INTO :NEW.ID_REGION
    FROM LAROATLB_REGION_CLIENTE;
END;


CREATE OR REPLACE TRIGGER LAROATLB_ID_CITA
  BEFORE INSERT 
  ON LAROATLB_CITA
  FOR EACH ROW
DECLARE
BEGIN
  SELECT NVL(MAX(ID_CITA),0)+1 INTO :NEW.ID_CITA
  FROM LAROATLB_CITA;
END;


CREATE OR REPLACE TRIGGER LAROATLB_ID_VETERINARIO
  BEFORE INSERT 
  ON LAROATLB_VETERINARIO
  FOR EACH ROW
DECLARE
BEGIN
  SELECT NVL(MAX(ID_VETERINARIO),0)+1 INTO :NEW.ID_VETERINARIO
  FROM LAROATLB_VETERINARIO;
END;

CREATE OR REPLACE TRIGGER LAROATLB_ID_TRATAMIENTO
  BEFORE INSERT 
  ON LAROATLB_TRATAMIENTO
  FOR EACH ROW
DECLARE
BEGIN
  SELECT NVL(MAX(ID_TRATAMIENTO),0)+1 INTO :NEW.ID_TRATAMIENTO
  FROM LAROATLB_TRATAMIENTO;
END;


CREATE OR REPLACE TRIGGER LAROATLB_ID_RAZA
  BEFORE INSERT 
  ON LAROATLB_RAZA
  FOR EACH ROW
DECLARE
BEGIN
  SELECT NVL(MAX(ID_RAZA),0)+1 INTO :NEW.ID_RAZA
  FROM LAROATLB_RAZA;
END;

CREATE OR REPLACE TRIGGER LAROATLB_ID_ESPECIE
  BEFORE INSERT 
  ON LAROATLB_ESPECIE
  FOR EACH ROW
DECLARE
BEGIN
  SELECT NVL(MAX(ID_ESPECIE),0)+1 INTO :NEW.ID_ESPECIE
  FROM LAROATLB_ESPECIE;
END;

-- Triggers Mayus
CREATE OR REPLACE TRIGGER LAROATLB_MAYUS_CLIENTE
BEFORE INSERT
ON LAROATLB_CLIENTE
FOR EACH ROW
BEGIN
    :NEW.NOMBRE := UPPER(:NEW.NOMBRE);
    :NEW.APELLIDO1 := UPPER(:NEW.APELLIDO1);
    :NEW.APELLIDO2 := UPPER(:NEW.APELLIDO2);
END;

CREATE OR REPLACE TRIGGER LAAB_MAYUS_SECRE
BEFORE INSERT
ON LAROATLB_SECRETARIA
FOR EACH ROW
BEGIN
    :NEW.NOMBRE := UPPER(:NEW.NOMBRE);
    :NEW.APELLIDO1 := UPPER(:NEW.APELLIDO1);
    :NEW.APELLIDO2 := UPPER(:NEW.APELLIDO2);
    :NEW.EMAIL := UPPER(:NEW.EMAIL);
END;

CREATE OR REPLACE TRIGGER LAROATLB_MAYUS_VETE
BEFORE INSERT
ON LAROATLB_VETERINARIO
FOR EACH ROW
BEGIN
    :NEW.NOMBRE := UPPER(:NEW.NOMBRE);
    :NEW.APELLIDO1 := UPPER(:NEW.APELLIDO1);
    :NEW.APELLIDO2 := UPPER(:NEW.APELLIDO2);
    :NEW.EMAIL := UPPER(:NEW.EMAIL);
END;


CREATE OR REPLACE TRIGGER trg_descuento_producto
AFTER INSERT ON LAROATLB_DETALLE_PRODUCTO_TRATAMIENTO
FOR EACH ROW
DECLARE
    v_stock_actual NUMBER;
BEGIN
    -- Obtener el stock actual del producto
    SELECT STOCK INTO v_stock_actual
    FROM LAROATLB_PRODUCTO
    WHERE ID_PRODUCTO = :NEW.ID_PRODUCTO;

    -- Restar la cantidad utilizada
    v_stock_actual := v_stock_actual - :NEW.CANTIDAD;

    -- Actualizar la cantidad del producto en la tabla de productos
    UPDATE LAROATLB_PRODUCTO
    SET STOCK = v_stock_actual
    WHERE ID_PRODUCTO = :NEW.ID_PRODUCTO;

    -- Verificar si la cantidad de producto llegó a 0 o menos
    IF v_stock_actual <= 0 THEN
        -- Si el stock es 0 o menor, generar un error
        RAISE_APPLICATION_ERROR(-20001, 'ALERTA: El producto ' || :NEW.ID_PRODUCTO || ' ha llegado a 0 cantidad');
    END IF;
END;
/


